# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --editable .[test]
    - name: mypy type checks
      run: |
        python run_mypy.py
    - name: Lint with ruff
      run: |
        ruff check --output-format=github .
    - name: Test with pytest
      run: |
        pytest --cov=pylisp --cov-report=xml --cov-report=term tests/
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
